

# 一、Go中的错误处理

> defer
>
> recover
>
> panic 
>
> 三个的基础只是



## 1. defer

让本段代码在该函数内容都执行完毕后最后执行



## 2. recover

阻止因为panic而导致程序崩溃终止运行，recover在panic之后执行，保证程序即使panic了仍然继续执行。

**recover必须在defer中执行**：这样能保证在goroutine panic之后执行。 （具体见下面panic中3)）

## 3. panic

> - `panic` 只会触发当前 Goroutine 的 `defer`；
> - `recover` 只有在 `defer` 中调用才会生效；
> - `panic` 允许在 `defer` 中嵌套多次调用；



1）`panic` 只会触发当前 Goroutine 的 `defer`：

如下在goroutine被panic终止了，但只有这个goroutine有成功执行了defer，main函数中没有执行

```go
func main() {
	defer println("in main")
	go func() {
		defer println("in goroutine")
		panic("panic了")
	}()

	time.Sleep(1 * time.Second)
}

$ go run main.go
in goroutine
panic:panic了

=====================如果去掉func()前面的go将会执行main goroutine的defer=================
in goroutinein main
panic: panic了
```



2） `recover` 只有在发生 `panic` 之后调用才会生效



- 如果recover发生在panic之前，则无效。

  直接将recover语句写在panic后面是无效的，因为panic之后不会执行。而放在panic之前本身就是对panic无效的。 因此只能放在defer里面，保证panic之后正确执行

```go
func main() {
	defer fmt.Println("in main")
	if err := recover(); err != nil {
		fmt.Println(err)
	}

	panic("unknown err")
}

$ go run main.go
in main
panic: unknown err

goroutine 1 [running]:
main.main()
	...
exit status 2
```



- 如下发生在之前

```go
func main() {
	defer func() {
		fmt.Println("in main")
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	panic("unknown err")
}
```





3） 多次调用panic不会影响defer的执行



```go
func main() {
	// 栈[0]:压入栈后继续执行1 panic once
	defer fmt.Println("main等所有执行完毕后执行")
	// 栈[1]:压入站先
	defer func() {
		// 执行输出第二个
		fmt.Println("No2.")
		// 栈[2]:暂时压入栈
		// 取出栈[2]:
		defer func() {
			// 执行输出第三个
			fmt.Println("No3.")
			// 执行输出panic 3
			panic("2 panic again and again")
		}()
		// 执行输出panic 2
		panic("panic again")
	}()
	// 执行输出panic 1
	fmt.Println("No1.")
	panic("1 panic once")
}
```

上面代码：输出分析

- 遇到defer首先压入栈，然后继续执行后面的内容
- 如果执行过程中遇到了panic，则在panic中输出panic内容
- 执行完当前func的输出以及panic之后，从栈中拿出对应defer执行

```
No1.
No2.
No3.
main等所有执行完毕后执行
panic: 1 panic once
	panic: panic again
	panic: 2 panic again and again
```





### 参考：

[Go语言程序设计原理](https://draveness.me/golang/docs/part2-foundation/ch05-keyword/golang-panic-recover/)